### ISSUE TITLE
Корректировки плана

### ISSUE THREAD

**Issue by ArRomanov** [12ok/aqa--diploma#1]
Первое, что хотел сказать - можете добавить ссылку на план в файл README, чтобы не искать план в репозитории, когда там станет больше файлов. А еще лучше сразу организовать в проекте директорию для хранения документации, ведь у вас будет больше, чем один файл.

## Перечень автоматизируемых сценариев
Хорошо оформили список. Есть пара замечаний.
1. Постарайтесь комбинировать проверки так, чтобы у вас было минимум тестов и максимум проверок. Например, писать тест на каждое поле, которое вы оставили пустым - не очень рационально. В одном тесте можно оставить все поля пустыми и проверить валидацию полей. Подумайте, как можно будет комбинировать и другие проверки.
2. Концовка, в блоке **Дополнительно** получилась какая-то смазанная. Например, если вы планируете писать API тесты, то сделайте отдельно такой пункт - UI (позитивные и/или негативные), API (позитивные и/или негативные). Потом проверка работы с двумя базами. Как, например, вы планировали организовать тест проверки этого момента, напишите, мне интересен ход ваших мыслей. Можно подумать о том, чтобы одновременно поднимать два контейнера с разными БД, а при запуске приложения и тестов передавать параметр с названием нужной базы или запускать последовательно тесты для каждой из БД с последовательным запуском приложения. В общем, здесь можно немного порассуждать.
3. Последний кейс можно отнести к негативным, а про обновление страницы - вы знаете ожидаемый результат? Какой баг мы можем предотвратить этим тестом?

## Перечень используемых инструментов с обоснованием выбора
Будет здорово, если вы действительно напишите обоснование выбора инструмента, то есть перечислите сильные стороны этих инструментов.
<details><summary>Лайфхак</summary>Можно написать, что вы имеете более глубокую экспертизу по конкретному инструменту по сравнению с альтернативными. Только не пишите так для всех инструментов.</details>

## Перечень и описание возможных рисков при автоматизации
Риски описаны очень хорошо, как раз отражают картину того, что может произойти у вас при выполнении задания. 

> При изменении GUI необходимо будет переписывать тесты

Вряд ли это произойдет, пока вы будете писать тесты. Такая ситуация потом - нормальное явление, это учитывают при принятии решения о внедрении автоматизации.

> Если изменятся тестовые карты, необходимо будет переписывать тесты

Почему вы так решили? Можно будет просто заменить тестовые данные и продолжить запускать тесты. Можете пояснить как вы рассуждали?

## Интервальная оценка с учётом рисков (в часах)
Здорово описаны тайминги по задачам. Хочу вас предупредить, что люди часто оценивают свои возможности (или возможности своей команды) позитивнее, чем есть на самом деле.
Пара советов:
1. Проанализируйте (если вдруг вы это не сделали), за какое время вы выполняли подобные задачи во время курса и помножьте на коэффициент сложности, который вы определите сами при сравнении уровня сложности у сделанной вами задачи и у той, которую предстоит выполнить.
2. Учтите свои риски в соответствии с планируемыми задачами. Добавьте к уже полученной оценки от 15% до 25%, в зависимости от степени риска. И желательно написать отдельно вашу оценку и отдельно оценку с учетом рисков.

**Comment by 12ok** [comment]
Сделано:
* отдельная директория для документов
* переписаны тесты с комбинированием разных значений в разных полях
* дописаны тесты для API
* дописаны тесты для БД
* более подробно расписаны инструменты
* при расчете времени увеличено кол-во часов на настройку проекта, добавлено время на непредвиденные риски

> Потом проверка работы с двумя базами. Как, например, вы планировали организовать тест проверки этого момента

У меня был вариант, поднимать в контейнерах обе БД и работать с ними по очереди: сначала полностью протестировать приложение на одной, потом на другой. По факту получается будут 2 раза прогоняться одни и те же тесты и будет 2 отчета для каждой СУБД. 

> Повторная оплата с той же карты
кейс можно отнести к негативным

Данный тест считаю позитивным, т.к. нет никаких ограничений на оплату по одной карте.

>  Про обновление страницы - вы знаете ожидаемый результат? Какой баг мы можем предотвратить этим тестом?

После обновления в целях безопасности форма должна быть пустая (все заполненные до этого данные не должны сохранятся).

> Если изменятся тестовые карты, необходимо будет переписывать тесты. Почему вы так решили? Можно будет просто заменить тестовые данные и продолжить запускать тесты. Можете пояснить как вы рассуждали?

Если мы просто захардкодим данные карт и json, то их необходимо будет менять каждый раз при изменении данных.
Если же мы будем создавать объект Card использую данные из json, то могут быть следующие проблемы при изменении:
* если добавится еще хотя бы одна карта, то  нам в тестах придется дописывать метод для выбора рандомной карты для определенного теста
* если помимо номера и статуса появятся еще какие-то поля в json, то нам необходимо будет переписывать класс Card и  методы его создания

**Comment by ArRomanov** [comment]
1. Очень понравился ход ваших мыслей, почти со всем с вами согласен. 
По поводу объекта карты я бы с вами подискутировал немного, но давайте оставим все так, а далее решим, как усовершенствовать механизм выбора и использовании карт в тестах, пока придерживайтесь плана.
2. По поводу сценариев. Я немного переживаю, что вы не успеете реализовать такое количество тестов, давайте еще попробуем немного сократить:
* Можно скомбинировать буквы и спецсимволы для заполнения данных карт в одном тесте. Либо все невалидные данные можно будет упаковать в csv и запускать в одном тесте.
* По поводу api. Если будем отправлять POST с пустым body, то наверняка карта не будет иметь значения. Подозреваю, что в url тип карты не учитывается, только кредит или обычная покупка. Поэтому POST запрос с пустым body будет, вероятнее всего, одинаковым для разных карт.
3. Что касается двух образов БД, здесь с вами согласен. Еще, думаю, нужно будет само  приложение упаковать в контейнер и поднимать два экземпляра на разных портах и прогонять тесты сначала на одной связке, затем на другой. Я еще уточню у Ильназа, будет ли это удачной реализацией в нашем случае.
4. По поводу обоснования инструментов. Здесь просто хочу выразить свое восхищение. Ощущение, что используете эти инструменты не один год. Респект!

В общем, план отличный. И будет отлично, если мы его реализуем, минимально от него отклонившись.
