### ISSUE TITLE
Комментарии по дипломной работе

### ISSUE THREAD

**Issue by 12ok** [12ok/aqa--diploma#2]
1. Тестов получилось много: по 18 на каждый тип оплаты и 15 на API. Комбинировать пыталась, но при разных комбинациях вылезали разные ошибки. Поэтому пришлось добавить еще тестов на проверку конкретного поля. 
1. Так как в одном тесте несколько проверок, то тест падает при первой же ошибке. Есть ли механизм "заставить" тест дойти до конца? 
1. Так как нет спецификации, то нет понимания какой верный текст ошибки у полей.
На данном этапе считала, что если поле не заполнено, то текст "Поле обязательно для заполнения", если не верный формат(недопустимые символы, недопустимое кол-во символов), то "Неверный формат".
1. Карта не из списка, должна ли записываться в БД. Тест пока сделан, что не должна. Но по логике, если карта отправляется на сервер проверки - то должна. Как поступить?
1. В таблице `order_entity` в БД есть поля `credit_id`  и `payment_id`. Так как нет никаких внешних ключей, то сложно понять взаимосвязь таблиц. Правильно ли, что `credit_id` должен содержать `bank_id` из таблицы `credit_request_entity`, а  `payment_id` должен содержать `transaction_id` из таблицы `payment_entity`? На данный момент проверка сделана, что из обеих таблиц запись идет в  `payment_id`.
1. Нужно ли в API тесты добавить и проверку БД?
1. Нужно ли написать API тесты и для банковских сервисов?
1. На данном этапе проверено на обеих БД. Но пока только путем:
    * поднятие контейнера с MYSQL
    * прогон тестов
    * остановкой контейнера с  MySQL
    * поднятие PostgreSQL
    * исправление URL в коде тестов
    * прогон тестов 
    
Сейчас буду думать и шаманить как бы это сделать нормально.

**Comment by ArRomanov** [comment]
По вашим вопросам:
1. Предложения по оптимизации в отдельном комментарии.
2. Либо оптимизируем так, чтобы была одна проверка, либо можно обратить внимание на конструкцию softassert в selenide - https://github.com/selenide/selenide/wiki/SoftAssertions. Делаются все проверки и только в конце теста общий результат. Тест упавший, если хоть одна проверка не прошла. Таким подходом лучше не особо увлекаться, но допустимо.
3. Можете сделать об этом ишью, то есть предложить унифицировать сообщения об ошибках для разных кейсов. Спецификации нет, поэтому импровизируем.
4. Карта не записывается в БД, вы хотели сказать запись о транзакции. Ну, если считать, что наш платежный шлюз не настоящий, а всего лишь заглушка, то будем считать, что всплывающего окна с ошибкой достаточно и можно опустить проверку записи в БД.
5. Похоже, что credit_id и payment_id должны ссылаться на разные таблицы, как вы и написали. Но этот вопрос я еще уточню, точнее уточню, умышленная это ошибка или случайная.
6. Написал в своих предложениях. Если кратко, то достаточно проверки в одном месте, мне кажется, что лучше в api тестах.
7. Думаю, что нет, это достаточно низкий уровень, чтобы мы это тестировали. Все равно, что начать писать юнит тесты для сервисов.
8. Это еще обсудим в слаке

**Comment by ArRomanov** [comment]
По ревью:
По инструкции:
1. 

> собрать образ командой docker image build -t node-app:1.0

не нужно указывать этот шаг, контейнер соберется в любом случае при запуске docker-compose
2. Если у вас подключен allure, то напишите в инструкции команды для генерации отчета allure, а то чего смотреть стандартный отчет, если есть возможность.

По классу для работы с БД:
1. Данные для подключения к БД тоже лучше задавать динамически, из проперти. Чтобы без проблем запускать тесты разными способами можно делать так `String url = System.getProperty("db.url", "url по умолчанию");` и всегда будет какое-то значение.
2. Вместо того, чтобы 3 раза вызывать `runner.update` в `clearDB `можно вызвать один раз, а передать строку из трех конструкций delete, разделенных точкой с запятой.
3. В методе `getOrderById `всю конструкцию if можно заменить строкой `return countOrderById > 0;`. И вообще, если вы возвращаете boolean, то метод принято называть **isSomething**, **hasSomething** и тд, чтобы ответом было да/нет.

По api тестам:
1. Данные об url и о портах должны быть переменными и передаваться из проперти при запуске.
2. Методы проверки GET вместо POST убрать. Написанием таких тестов мы тратим драгоценное время, но не проверяем функционал.
3. Методы с пустым body можно убрать, ошибка будет 100%
4. Остальные методы можно сгруппировать в параметризированные тесты и передавать в параметрах номер карты или url (покупка/кредит), только параметры передавать не через **CsvFileSource**, чтобы не плодить много файлов, а через **CsvSource**, чтобы сразу в аннотации указать параметры.
5. Добавьте в build.gradle `testImplementation 'io.qameta.allure:allure-rest-assured:2.13.0'`, а в создание **requestSpec** строку `.addFilter(new AllureRestAssured())` и у вас в отчете будут прикрепляться логи каждого api теста, это очень удобно для анализа тестов.

TestFormPaymentByCard и TestFormPaymentByCredit:
1. Нужно в **BeforeAll** зарегистрировать лисенер, чтобы к отчету прикреплялись скрины - `SelenideLogger.addListener("allure", new AllureSelenide());`
2. Текущий месяц и год - валидные данные, можно удалить тест, а в невалидные поставить прошлый месяц и прошлый год (можно два разных теста)
3. Давайте проверки в БД перенесем в api тесты. Все-таки UI проверяют поведение страницы, а мы портим все это упавшими проверками в БД. А вот проверить записи в бд можно после валидных api тестов. Либо оставим проверки в БД оставим в UI, но только для позитивных тестов и только после проверки успешности/неуспешности и добавим сообщения об ошибке третьим параметром в assert, чтобы было очевидно, почему 2 не равно 3, например, а то, глядя в отчет на эту ошибку, вообще непонятно, что проверялось.
4. По поводу самих проверок в БД, мне они показались слишком запутанными и сложными. Но, глядя на сами таблицы в БД, вообще не хочется никаких проверок писать. Я посоветуюсь с Ильназом в понедельник, спрошу у него, какие проверки будут актуальнее. Пока оставим вопрос открытым.
5. Предлагаю для обсуждения такой вариант распределение тестов для улучшения структуры: один тест с валидными данными, и пять тестов с проверкой одного поля в каждом тесте (остальные 4 поля валидные). Получается 6 тестов в классе. Но те, которые с проверкой для поля делаем параметризированными и передаем тестовые данные для одного поля и текст ошибки в параметрах (текст ошибки даже не обязательно, можно проверять по наличию ошибки). И тесты будут понятно написаны - проверка поля Номер карты, проверка поля Месяц и тд, при этом анализ покрытия упростится и, скорее всего, немного вырастит скорость тестов.

**Comment by 12ok** [comment]
> Данные для подключения к БД тоже лучше задавать динамически, из проперти. Чтобы без проблем запускать тесты разными способами можно делать так String url = System.getProperty("db.url", "url по умолчанию"); и всегда будет какое-то значение.

что-то не получается, null приходит (если без дефолтного значения)
в коде закомментированы мои попытки
сделала в блоке static чтение файла properties

> Вместо того, чтобы 3 раза вызывать runner.update в clearDB можно вызвать один раз, а передать строку из трех конструкций delete, разделенных точкой с запятой.

вот такой код выдает ошибку
`@SneakyThrows
     public static void clearDB() {
         try (val conn = DriverManager.getConnection(url, userDB, password)) {
             runner.update(conn, "DELETE FROM credit_request_entity; DELETE FROM payment_entity; DELETE FROM order_entity;");
         }
     }`

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELETE FROM payment_entity; DELETE FROM order_entity' at line 1 Query: DELETE FROM credit_request_entity; DELETE FROM payment_entity; DELETE FROM order_entity; Parameters: []`

> Данные об url и о портах должны быть переменными и передаваться из проперти при запуске.

Но в проперти же их нет
Данные данные по url и порту из описания проекта
Url покупка/кредит взяты были из jar файла приложения

**Comment by 12ok** [comment]
Сделано:
* частично настроен allure (пока без "красоты")
* убраны "лишнее" тесты из API
* Api тесты сгруппированы в параметризированные, где передается url покупка/кредит
* очистка БД добавлена после каждого теста
* скорректированны тесты проверки БД
* тесты формы тоже сделала параметризированные для каждого поля. Теперь тестов стало еще больше. Тут наверное можно вместо 3-х невалидных варинтов, оставит только один, например, где есть и буквы и цифры и спецсимволы.
* отдельными тестами идут 
    * approved/declined/noDb карты
    * все значение больше допустимого, т.к. там идет проверка на значения в полях, а не на какие-либо ошибки
    * тест проверки валидации полей месяц/год при пустом владельце, т.к. там отдельный баг

**Comment by ArRomanov** [comment]
1. Property. Чтобы запустить сервис из jar файла с определенной базой нужно передать параметр при запуске - `java -Dspring.datasource.url='jdbc:postgresql://localhost:5432/app' -jar artifacts/aqa-shop.jar` и, соответственно, убрать это свойство из application.property. Данные для логина и пароля от базы данных можно оставить в файле с тем учетом, что в разных БД они будут такими же. 
Проперти в тест передаются так: 
* в самом коде просто `url = System.getProperty("db.url");`
* в build.gradle `systemProperty 'db.url', System.getProperty('db.url', 'jdbc:mysql://localhost:3306/app')` (как мы делали режим headless для браузера только добавим дефолтное значение)
* а при запуске тестов передадим нужные проперти с адресом БД `gradle test -Ddb.url='jdbc:postgresql://localhost:5432/app'` (если не передадим, то будет использоваться дефолт из build.gradle, например логин и пароль)
2. Объединение нескольких запросов в один нормально работает по умолчанию для postgres и запрещено для mysql, там необходимо установить дополнительный флаг, поэтому оставляем три отдельных запроса, чтобы не заморачиваться
3. Основные url(localhost) и port(8080) приложения могут изменится, можно сделать по аналогии с первым пунктом - прописываем в build.gradle app.url и app.port, задаем значения по умолчанию, а в коде вызываем System.getProperty("app.url") и System.getProperty("app.port") соответственно

**Далее**
1. Уберите проверки в БД для негативных апи тестов, то есть для тех, которые возвращают 400 и 500 - это лишний код, здесь нет необходимости проверять (не)занесение в БД , его не будет 100%
2. Проверки для позитивных тестов тоже слишком усложненные. У нас тут и нечего особо проверять, статус и сумма (если не кредит и записывается в БД копейками), должно быть по одной записи в двух таблицах. Используя подзапрос и полагаясь на то, что у нас точно только записи одной транзакции, мы точно убедимся, что в обеих таблицах есть запись и записан нужный статус и сумма.

    ```
    select status, amount 
    from payment_entity 
    where transaction_id=
    (select payment_id 
    from order_entity
    order by created desc
    limit 1);
    ```
    ```
    select status 
    from credit_request_entity 
    where bank_id=
    (select credit_id 
    from order_entity
    order by created DESC
    limit 1);
    ```
3. Убрать тесты `Отправка формы с невалидной датой и пустым владельцем` и `Отправка формы с невалидными значениями (max)` как из кредита, так и из покупки. Мы проверили все поля по отдельности, зачем еще комбинировать? Проверка максимальной строки опустим тоже, нам нужна функциональность и минимум тестов
4. Здесь покажу кейсы, которые нужно удалить. Часть случаев переоцененная, нам не нужно тестировать отдельно спецсимволы - если поле не пропускает буквы, то и не пропустит спецсимволы, потому что тип у поля `num` или `int` и тд. После 3 и 4 пункта по мои подсчетам должно уйти 26 или более тестов
![image](https://user-images.githubusercontent.com/23121947/70574568-77227980-1bb5-11ea-831f-5431e2f3cb1e.png)
![image](https://user-images.githubusercontent.com/23121947/70574520-578b5100-1bb5-11ea-8ef8-c9718dddf3e5.png)
![image](https://user-images.githubusercontent.com/23121947/70574648-a6d18180-1bb5-11ea-841e-166e2e3d1716.png)
![image](https://user-images.githubusercontent.com/23121947/70574710-c799d700-1bb5-11ea-860f-6b9bbb433983.png)
![image](https://user-images.githubusercontent.com/23121947/70574760-e4360f00-1bb5-11ea-8554-e306207f1fd4.png)
5. Вы в порыве сделать максимально хорошо невероятно усложнили код. Мотивация - отлично, но надо знать меру. Нам нужно прогонять тесты максимально быстро, а еще и поддерживать в дальнейшем. И вы написали только тесты на две формы. А представьте размах для простенького интернет магазина? Страшно представить. Можно было убрать и больше тестов, в реальном проекте такая роскошь часто непозволительна, но я не могу перечеркнуть ваши старания. Так что учтите на будущее, всегда должен быть баланс, мы не можем жертвовать временем на прогон и поддержку ради 100% тестового покрытия. Тем более мы его никогда не получим, оно недостижимо и стремление к нему может свести с ума.
